import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center pt-24">
          <h1 className="text-4xl font-bold">Next.js Routing Demo</h1>
          {children}
        </main>
      </body>
    </html>
  );
}
