import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center pt-24">
          <div className="flex flex-col-reverse">
            <h1 className="text-4xl font-bold">Next.js Routing Demo</h1>
            <Link href="/" className="text-blue-600 text-left">
              ←/app/page.tsx
            </Link>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
